import type { MetricDefinition } from '@/types/telemetry'

export const METRIC_DEFINITIONS: MetricDefinition[] = [
  // Motion
  {
    metricId: 'motion.speed',
    label: 'Speed',
    unit: 'km/h',
    group: 'motion',
    precision: 0,
    min: 0,
    max: 200,
    warningHigh: 140,
    criticalHigh: 160,
    sparklineEnabled: true,
    displayOrder: 1,
  },
  {
    metricId: 'motion.acceleration',
    label: 'Acceleration',
    unit: 'm/s²',
    group: 'motion',
    precision: 2,
    min: -5,
    max: 5,
    sparklineEnabled: false,
    displayOrder: 2,
  },
  {
    metricId: 'motion.distance',
    label: 'Distance',
    unit: 'km',
    group: 'motion',
    precision: 1,
    min: 0,
    max: 999999,
    sparklineEnabled: false,
    displayOrder: 3,
  },

  // Fuel / Energy
  {
    metricId: 'fuel.level',
    label: 'Fuel Level',
    unit: '%',
    group: 'fuel',
    precision: 1,
    min: 0,
    max: 100,
    warningLow: 20,
    criticalLow: 10,
    sparklineEnabled: true,
    displayOrder: 1,
  },
  {
    metricId: 'fuel.consumption_rate',
    label: 'Consumption Rate',
    unit: 'L/h',
    group: 'fuel',
    precision: 1,
    min: 0,
    max: 500,
    warningHigh: 400,
    sparklineEnabled: true,
    displayOrder: 2,
  },

  // Thermal
  {
    metricId: 'thermal.coolant_temp',
    label: 'Coolant Temperature',
    unit: '°C',
    group: 'thermal',
    precision: 1,
    min: 0,
    max: 150,
    warningHigh: 95,
    criticalHigh: 105,
    warningLow: 10,
    sparklineEnabled: true,
    displayOrder: 1,
  },
  {
    metricId: 'thermal.oil_temp',
    label: 'Oil Temperature',
    unit: '°C',
    group: 'thermal',
    precision: 1,
    min: 0,
    max: 160,
    warningHigh: 110,
    criticalHigh: 130,
    sparklineEnabled: true,
    displayOrder: 2,
  },
  {
    metricId: 'thermal.exhaust_temp',
    label: 'Exhaust Temperature',
    unit: '°C',
    group: 'thermal',
    precision: 0,
    min: 0,
    max: 700,
    warningHigh: 550,
    criticalHigh: 650,
    sparklineEnabled: false,
    displayOrder: 3,
  },

  // Pressure / Pneumatics
  {
    metricId: 'pressure.brake_main',
    label: 'Brake Main Reservoir',
    unit: 'bar',
    group: 'pressure',
    precision: 1,
    min: 0,
    max: 10,
    warningLow: 7,
    criticalLow: 5,
    sparklineEnabled: true,
    displayOrder: 1,
  },
  {
    metricId: 'pressure.brake_pipe',
    label: 'Brake Pipe',
    unit: 'bar',
    group: 'pressure',
    precision: 1,
    min: 0,
    max: 6,
    warningLow: 4.5,
    criticalLow: 4.0,
    sparklineEnabled: true,
    displayOrder: 2,
  },
  {
    metricId: 'pressure.oil',
    label: 'Oil Pressure',
    unit: 'bar',
    group: 'pressure',
    precision: 1,
    min: 0,
    max: 8,
    warningLow: 3,
    criticalLow: 2,
    sparklineEnabled: false,
    displayOrder: 3,
  },

  // Electrical
  {
    metricId: 'electrical.traction_voltage',
    label: 'Traction Voltage',
    unit: 'V',
    group: 'electrical',
    precision: 0,
    min: 0,
    max: 3000,
    warningLow: 2600,
    criticalLow: 2400,
    warningHigh: 2900,
    criticalHigh: 3000,
    sparklineEnabled: true,
    displayOrder: 1,
  },
  {
    metricId: 'electrical.traction_current',
    label: 'Traction Current',
    unit: 'A',
    group: 'electrical',
    precision: 0,
    min: 0,
    max: 2000,
    warningHigh: 1600,
    criticalHigh: 1800,
    sparklineEnabled: true,
    displayOrder: 2,
  },
  {
    metricId: 'electrical.battery_voltage',
    label: 'Battery Voltage',
    unit: 'V',
    group: 'electrical',
    precision: 1,
    min: 0,
    max: 120,
    warningLow: 100,
    criticalLow: 90,
    sparklineEnabled: false,
    displayOrder: 3,
  },
]

export const METRIC_GROUPS: Record<string, string> = {
  motion: 'Motion',
  fuel: 'Fuel & Energy',
  thermal: 'Thermal',
  pressure: 'Pressure & Pneumatics',
  electrical: 'Electrical',
}
